apiVersion: v2
appVersion: "1.16.0"
version: 0.1.0
name: z-dax
description: Helm as stack for zsmartex cryptocurrency exchange

dependencies:
  - name: adminer
    repository: https://cetic.github.io/helm-charts
    version: 0.2.1
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.5.1
  - name: elasticsearch
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 19.8.1
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts
    version: 0.35.0
  - name: schema-registry
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.0.0
  - name: console
    repository: https://charts.redpanda.com
    version: 0.6.4
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.24.1
  - name: questdb
    repository: https://helm.questdb.io
    version: 0.30.0
