# Default values for z-dax.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Adminer database management
adminer:
  config:
    design: pepa-linha-dark
    externalserver: postgresql
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    hosts:
      - adminer.k8s-learn.com

# Postgresql database
postgresql:
  auth:
    username: root
    password: changeme
  primary:
    persistence:
      storageClass: k8slvm
      size: 10Gi
  volumePermissions:
    enabled: true

# Elasticsearch search engine
elasticsearch:
  master:
    replicaCount: 3
    persistence:
      storageClass: k8slvm
      size: 10Gi
    autoscaling:
      enabled: false
      minReplicas: 3
      maxReplicas: 10
  data:
    replicaCount: 3
    persistence:
      storageClass: k8slvm
      size: 10Gi
    autoscaling:
      enabled: false
      minReplicas: 3
      maxReplicas: 10
  ingress:
    enabled: true
    tls: false
    ingressClassName: nginx
    extraHosts:
      - name: elasticsearch-svc
        path: /
      - name: elasticsearch.k8s-learn.com
        path: /
    secrets: []
  security:
    tls:
      restEncryption: false

# Kafka
strimzi-kafka-operator:
  replicas: 1
  mavenBuilder:
    image:
      registry: docker.io
      repository: zsmartex
      image: maven-builder
      tag: latest

schema-registry:
  nameOverride: schema-registry
  fullnameOverride: schema-registry
  replicaCount: 1
  kafka:
    enabled: false
  externalKafka:
    brokers:
      - PLAINTEXT://strimzi-cluster-kafka-bootstrap:9092

console:
  console:
    config:
      kafka:
        brokers:
          - strimzi-cluster-kafka-bootstrap:9092
        schemaRegistry:
          enabled: true
          urls: ["http://schema-registry:8081"]
        protobuf:
          enabled: true
          schemaRegistry:
            enabled: true
            refreshInterval: 5m
      connect:
        enabled: true
        clusters:
          - name: connect-cluster
            url: http://strimzi-cluster-connect-api:8083
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: console.k8s-learn.com
        paths:
          - path: /
            pathType: ImplementationSpecific

# Questdb timeseries database
questdb:
  persistence:
    enabled: true
    size: 10Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: questdb.k8s-learn.com
        paths:
          - /
